project:
  type: website

website:
  title: "OnlyBlends.Mixer.Docs"
  navbar:
    left:
      - index.qmd
      

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
     